### ISSUE TITLE
Release policy: Give every build a new version number

### ISSUE THREAD

**Issue by cmorty** [Qalculate/qalculate-gtk#112]
I didn't research this. I just wanted to draw some attention to thus issue: https://github.com/C4illin/Choco-Packages/issues/1 
It seems like the installer was changed without changing the version. This caused some chocolatey packaging issues.

**Comment by C4illin** [comment]
This happened with version 3.2.0 and 2.9.0 but if I recall correctly it was only the windows version that was affected, so I can see why there wasn't any change in the version number since it only affected a certain system. Still, I would appreciate if the version number changed to reflect small fixes.
