### ISSUE TITLE
Enhancement: preference that disables automatic update check

### ISSUE THREAD

**Issue by myspaghetti** [Qalculate/qalculate-gtk#133]
Hi. Love qalculate, love qalculate-gtk, been using it for years and years. I'd like qalculate-gtk to have a setting that disables the automatic update check. Something like `automatic_version_check=0` or a checkbox in the GUI's preferences panel.

**Comment by hanna-kn** [comment]
If you set `last_version_check=3020-02-08` automatic update checks should be disabled for 1000 years.

Do you have a specific reason for disabling automatic update checks? Normally Qalculate will only check for new versions every second week and only show a message once for every new version. Some have reported version checks (and messages) on every start of the application (presumably because of failure to save configuration), but this was assumed as fixed in versions >= 3.5.

**Comment by myspaghetti** [comment]
>Do you have a specific reason for disabling automatic update checks?

Nope. Thanks for the tip!
