### ISSUE TITLE
When calculation a resistance via V/A the default unit is W/A² instead of ohmes

### ISSUE THREAD

**Issue by SparkyCola** [Qalculate/qalculate-gtk#16]
Hi, I experience the above issue when I use any calculation `x V/y A`i get W/A² which is not wrong (I assume haven't actually checked) but not common and rather confusing since ohm is the common unit, but this is only shown when I force it with `to ohm`. 
However, I'm not shure if this bug belongs here or into the lib repo. I'm using Qalculate V0.9.7 on Ubuntu 16.10.

**Comment by hanna-kn** [comment]
Is "Convert to Optimal Unit" (in Mode->Unit Display menu) activated?
With this option activated W/A² is automatically converted to ohm in the latest version (0.9.12).

**Comment by SparkyCola** [comment]
Thanks for the tip, that "workaround" works great. I'm going to update as soon as the Ubuntu 16.10 repo catches up.

**Comment by Yann48** [comment]
root@trochet-ubuntu17:~# snap info qalculate
argument: "qalculate"
warning:  ceci n'est pas un paquet Snap valide
erreur : aucun paquet Snap valide n'a été indiqué
   Comment avoir la dernière version si snap ne connait pas qalculate ou Qalculate?

**Comment by hanna-kn** [comment]
> root@trochet-ubuntu17:~# snap info qalculate
> argument: "qalculate"
> warning: ceci n'est pas un paquet Snap valide
> erreur : aucun paquet Snap valide n'a été indiqué
> Comment avoir la dernière version si snap ne connait pas qalculate ou Qalculate?

Snap finds (and installs) Qalculate! without any issues on my unmodified Ubuntu 16.04, Ubuntu 17.04 systems and on my main Arch Linux system. Ubuntu 15.04 is not supported.

```
~$ snap info qalculate
name:      qalculate
summary:   "The ultimate desktop calculator"
publisher: h-k
description: |
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is small
  and simple to use but with much power and versatility underneath. Features
  include customizable functions, units, arbitrary precision, plotting, and a
  user-friendly interface.
  
  Graphical user interface, CLI and gnuplot are included in the package.
channels:               
  stable:    2.1.0 (10) 73MB -
  candidate: 2.1.0 (10) 73MB -
  beta:      2.1.0 (10) 73MB -
  edge:      2.1.0 (10) 73MB -
```

**Comment by Yann48** [comment]
Boujour,

 

Today it's the same for me. But not yesterday.

So I try: 

 

trochet@trochet-ubuntu17:~$ sudo snap install qalculate
[sudo] Mot de passe de trochet : 
erreur : snap "qalculate" not found



Very curious, is'nt it?

 

 

 

> Message du 02/11/17 21:04
> De : "Hanna Knutsson" 
> A : "Qalculate/qalculate-gtk" 
> Copie à : "Yann48" , "Comment" 
> Objet : Re: [Qalculate/qalculate-gtk] When calculation a resistance via V/A the default unit is W/A² instead of ohmes (#16)
> 
>

> root@trochet-ubuntu17:~# snap info qalculate
> argument: "qalculate"
> warning: ceci n'est pas un paquet Snap valide
> erreur : aucun paquet Snap valide n'a été indiqué
> Comment avoir la dernière version si snap ne connait pas qalculate ou Qalculate?


> Snap finds (and installs) Qalculate! without any issues on my unmodified Ubuntu 16.04, Ubuntu 17.04 systems and on my main Arch Linux system. Ubuntu 15.04 is not supported.

~$ snap info qalculate
name: qalculate
summary: "The ultimate desktop calculator"
publisher: h-k
description: |
Qalculate! is a multi-purpose cross-platform desktop calculator. It is small
and simple to use but with much power and versatility underneath. Features
include customizable functions, units, arbitrary precision, plotting, and a
user-friendly interface.

Graphical user interface, CLI and gnuplot are included in the package.
channels: 
stable: 2.1.0 (10) 73MB -
candidate: 2.1.0 (10) 73MB -
beta: 2.1.0 (10) 73MB -
edge: 2.1.0 (10) 73MB -

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Qalculate/qalculate-gtk","title":"Qalculate/qalculate-gtk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Qalculate/qalculate-gtk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hanna-kn in #16: \u003e root@trochet-ubuntu17:~# snap info qalculate\r\n\u003e argument: \"qalculate\"\r\n\u003e warning: ceci n'est pas un paquet Snap valide\r\n\u003e erreur : aucun paquet Snap valide n'a été indiqué\r\n\u003e Comment avoir la dernière version si snap ne connait pas qalculate ou Qalculate?\r\n\r\nSnap finds (and installs) Qalculate! without any issues on my unmodified Ubuntu 16.04, Ubuntu 17.04 systems and on my main Arch Linux system. Ubuntu 15.04 is not supported.\r\n\r\n```\r\n~$ snap info qalculate\r\nname: qalculate\r\nsummary: \"The ultimate desktop calculator\"\r\npublisher: h-k\r\ndescription: |\r\n Qalculate! is a multi-purpose cross-platform desktop calculator. It is small\r\n and simple to use but with much power and versatility underneath. Features\r\n include customizable functions, units, arbitrary precision, plotting, and a\r\n user-friendly interface.\r\n \r\n Graphical user interface, CLI and gnuplot are included in the package.\r\nchannels: \r\n stable: 2.1.0 (10) 73MB -\r\n candidate: 2.1.0 (10) 73MB -\r\n beta: 2.1.0 (10) 73MB -\r\n edge: 2.1.0 (10) 73MB -\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/Qalculate/qalculate-gtk/issues/16#issuecomment-341541590"}}}
