### ISSUE TITLE
[interface question] How do I shrink the interface to display only the things I need?

### ISSUE THREAD

**Issue by IvoAndonov** [Qalculate/qalculate-gtk#169]
I'm having trouble shrinking the interface to display only the things I need. Normally, the interface looks like image01. What I wanna have is the interface to look like the Windows 7 calculator - image02. How do I do that?

image01:
![image01](https://user-images.githubusercontent.com/41172201/85878757-e4100080-b7e1-11ea-8b85-a38a7f63591a.jpg)

image02:
![image02](https://user-images.githubusercontent.com/41172201/85878762-e4a89700-b7e1-11ea-8334-ec70f4f4efb8.jpg)

**Comment by hanna-kn** [comment]
That is currently not possible (unless you edit the code). The only options is to show the standard keypad, the programming keypad, or no keypad at all.

It should not be difficult to implement. The question is exactly what should be hidden/shown and how to activate this mode. 

The left keypad should of course be hidden, but it would be probably also make sense to replace the '±' and ';' buttons. To reduce the width of the window, some or all of the buttons and menus at the top of the keypad should be hidden, and possible also the menu bar (the width varies depending on font and language).

The mode should either be activated using a menu replacing the programming mode button ('P'), or a widget (arrow) between the left and right parts of the keypad. (There might be other options I haven't thought of.)

Personally, I would rather use the minimal mode and the keyboard instead of the keypad (but I guess it might be less efficient when using a touchscreen).

**Comment by foreachthing** [comment]
I, too, would like a "minimal", "normal", "advanced" and "full" mode. Or, however you want to call it. 
I'm a keyboard user and don't use the mouse for Q! so I don't need that many buttons on screen... 
The history is always visible on my Q!

**Comment by hanna-kn** [comment]
> I, too, would like a "minimal", "normal", "advanced" and "full" mode. Or, however you want to call it.

The question is, what should these keypad variants contain. The answer will probably be quite different for different users. 

Ideally the user would be able to select exactly which buttons to show, but I do not think it is feasible. It would be more realistic to allow users to select groups of buttons or provide different keypads for different usages (algebra, trigonometry, physics, etc., in addition to programming), but the first alternative creates layout issues and the second alternative has with likely overlapping usage.

> I'm a keyboard user and don't use the mouse for Q! so I don't need that many buttons on screen...

For keyboard users it might even make sense to hide the right part of the keypad (even though it would be a bit unorthodox).

> The history is always visible on my Q!

This variant make the issue more complicated. When the history is visible it makes more sense to reduce the height, rather than the width, of the keypad.

**Comment by IvoAndonov** [comment]
"Normal" mode should contain the buttons from image02. I don't wanna lose the +/- button or the X on Y power button. Also, "Normal" mode could have the small "equals" button removed because there's one already at the bottom, right next to the "+" and "-" buttons, so the one next to the results screen is unnecessary.

If I had the programming knowledge to edit the code, I would change it myself but I don't have it. I can read a code and only partially remove things which I did with gnome-screenshot but that program was much simpler than a calculator and I'm not sure I can do it without making a mess.

**Comment by hanna-kn** [comment]
Here is my first attempt:
![Skärmbild från 2020-06-27 16-49-56](https://user-images.githubusercontent.com/19703699/85925030-462a3d80-b896-11ea-9303-037ce9fb91c6.png)
I'm not entirely pleased with how it looks.

> Also, "Normal" mode could have the small "equals" button removed because there's one already at the bottom, right next to the "+" and "-" buttons, so the one next to the results screen is unnecessary.

The small "equals" button is also used as a stop button and an information widget (for warnings and errors).

**Comment by IvoAndonov** [comment]
> Here is my first attempt:
> I'm not entirely pleased with how it looks.
> 
> > Also, "Normal" mode could have the small "equals" button removed because there's one already at the bottom, right next to the "+" and "-" buttons, so the one next to the results screen is unnecessary.
> 
> The small "equals" button is also used as a stop button and an information widget (for warnings and errors).

I like the way it looks. Where can I download its source to compile from it? That is, if you have uploaded the commit of the new look.

**Comment by foreachthing** [comment]
@hanna-kn, just an idea, I don't know it's feasible (or makes much sense, while writing this...), instead of making "Standard", "Minimal" and "Programming" exclusive, make those as options. That way one could have "Minimal" and "Programming".

**Comment by hanna-kn** [comment]
Here is an alternative variant where the left keypad buttons are hidden independently, of other keypad modes, by clicking the arrow (placed in the middle when all buttons are shown). I've also replaced to fraction menu with a single toggle button.
![Skärmbild från 2020-06-28 13-55-35](https://user-images.githubusercontent.com/19703699/85946806-433b5580-b947-11ea-9469-075d257a556d.png)

> That way one could have "Minimal" and "Programming".

I assume that you mean the minimal keypad combined with the base conversion text, instead of "Exact", fractions, etc.

**Comment by IvoAndonov** [comment]
Works perfectly, hanna, exactly the way I wanted it! Thank you! :D
