### ISSUE TITLE
GDBUS.EXE

### ISSUE THREAD

**Issue by THX11** [Qalculate/qalculate-gtk#185]
Hi,

I enjoy using your calculator. Great upgrade to show / hide either keypad.

 **Issue**
GDBUS.EXE keeps running after qalculate.exe is closed.
 
Also, is it possible to add the feature, remember screen position for MS Windows?

Thank you.

**Comment by hanna-kn** [comment]
I am not able to reproduce the issue. On both Windows 7 and 10 gdbus.exe terminates shortly after qalculate.exe. Make sure that there are not any other processes (e.g. Inkscape) running that uses gdbus.

Remember window position option has now been added (deactivated by default).

**Comment by hanna-kn** [comment]
D-Bus is primarily used for inter-process communication. D-Bus is required by the GUI library used by Qalculate (gdbus.exe is not explicitly opened by the application), and is used for communication between different instances of Qalculate (primarily to activate a previous instance instead of opening a new one). No outgoing traffic is expected.

A lingering gdbus process should be harmless. It would however be interesting to know if the issue interferes with the D-Bus communication (what happens if another instance of Qalculate, with or without an expression provided from the command line, is opened?).

> I did not find _Remember window position_ in version 3.12.1

This feature will be included in the next version.

**Comment by THX11** [comment]
Thank you Hanna,

I don't want to waste your time.

I re-installed and events are now different.

Process explorer with single instance.
Apperance of gdbus.exe is only momentary then gdbus.exe ends.
![QalculateProcessExplorer](https://user-images.githubusercontent.com/70521199/91874552-b5207a00-ecbd-11ea-8f04-b38843bc3da2.PNG)
Same with multiple instances.

Keep up the good work.
