### ISSUE TITLE
Convert currency by typing in currency codes

### ISSUE THREAD

**Issue by kidimbwi** [Qalculate/qalculate-gtk#206]
currently if we want to convert us dollar to albanian lek we have to type out 57, dollar and pick out U.S. Dollar from the list the type in albanian or lek to select Albanian Lek from the popup suggestions. 

could you consider adding the ability to recognize currency codes when they are typed in ? so that when we type in usd, U.S. Dollars would be listed as a suggestion and when we type in all we would get the Albanian Lek as a suggestion.

Thank you.

**Comment by hanna-kn** [comment]
I would type `$57 to ALL` or `57USD to ALL` (if $ conflicts with local currency symbol), or just `$57` (if lek is the local currency).

Currency codes are case sensitive.

**Comment by kidimbwi** [comment]
Thank you for the suggestions, i did not know that currency codes are case sensitive. would you consider making them case insensitive ? this will enable users to skip having to hold down shift or enable caps in order to use currency codes in currency conversion.

**Comment by hanna-kn** [comment]
I decided not to make the currency codes case insensitive because of the potential conflicts, e.g. CUP (Cuban Pesos) and cup (≈ 0.237 L), and KGS and kilogram second (kgs). I will look into it again.

You also have the option to add keyboard shortcuts for individual units, or add derived units or variables with appropriate names (e.g. variable "usd" with value 1 USD).

**Comment by kidimbwi** [comment]
good suggestions, i'm continuing to find out that Qalculate! is even more fully featured than i knew.

i've noticed some interesting behaviour in the popup suggestions. 

- type in **CU** or **cu** and Cuban Pesos will be in the list of popup suggestions(the difference being in the location of the Cuban Peso suggestion in the popup list) but typing in **gb** will not bring up the British Pound as a suggestion while typing **GB** will.

typing in **CU**

![cu1](https://user-images.githubusercontent.com/65897337/100292224-e80e9d00-2f90-11eb-8dad-14bc1c08e773.png)

typing in **cu**

![cu2](https://user-images.githubusercontent.com/65897337/100292239-f361c880-2f90-11eb-9a0d-959ba83fd979.png)

typing in **GB** (interesting to note that the two other units suggested are not shown when **gb** is typed in)

![gb1](https://user-images.githubusercontent.com/65897337/100292264-04123e80-2f91-11eb-9a97-58d34a717b73.png)

typing in **gb**

![gb2](https://user-images.githubusercontent.com/65897337/100292281-0f656a00-2f91-11eb-8c3e-32aaef7c31e4.png)

- typing in **CUP** will give a user the option to select the Cuban Peso or Cup but typing in **cup** will only give a user the Cup suggestion. 

typing in **CUP**

![cup1](https://user-images.githubusercontent.com/65897337/100292485-ab8f7100-2f91-11eb-9859-9e5e01546ddf.png)

typing in **cup**

![cup2](https://user-images.githubusercontent.com/65897337/100292507-bcd87d80-2f91-11eb-9abe-2c8565ffdb4f.png)

so to summarise

- when a user types in **CU** or **cu** the popup suggestions are the same, the only difference is in the location of the Cuban Peso suggestion.
- when **GB** is typed in, the British Pound is suggested along with the Giga quantities of the Byte and the Becquerel. when **gb** is type in, nothing is suggested.
- when **CUP** is typed in both the Cuban Peso and the Cup are suggested, but when **cup** is typed in, only the Cup is suggested.

in my view, and from very limited testing, making currency codes case insensitive will do more good than harm. as seen in the last example, making the currency code case insensitive will give a user the same suggestions that we are getting now with case sensitive currency codes.

an alternative method, though maybe more complex, would be to detect the first currency code typed in and restrict the subsequent suggestions to currency codes. so for example, if a user types in "58 CUP to" the suggestions after "to" would only be currencies because it would not make sense to convert Cuban Pesos to Parsecs. this could be part of a larger "smart suggestions" feature where suggestions during unit conversions will be restricted to units that are convertible to the starting unit. so if a user starts by typing in "58 pound_force" then "to" when the user types in "n" the popup suggestions will be restricted to units which pound_force can convert to.

Thank you again for your interest and please have a look at this feature.

**Comment by hanna-kn** [comment]
The completion list is first updated by comparing the current text string with names of objects (units, etc.). This is always case-sensitive to reduce the number of matches. The resulting matches are shown at the top of the list.

Additional objects are added to the list by comparing words in the title of the object and the countries of currencies. By default this requires a minimum length of two characters.

To improve currencies matching, I will add case-insensitive name comparison to the latter ("gb" will then show GBP and "cup" will include CUP in the completion list). This change is of little consequence for other types of objects, since names with more than two characters seldom uses capital letters (and the name is often present in the title).

The completion behaviour can be customized in the preferences dialog.

> an alternative method, though maybe more complex, would be to detect the first currency code typed in and restrict the subsequent suggestions to currency codes.

This is complicated by the fact that a complete implementation requires that the expression (before "to") is calculated before completion (for all but the simplest expressions the final units of the result might be different from the units present in the expression).

**Comment by hanna-kn** [comment]
Case insensitive currency codes, case insensitive completion (as title completion), and restricted completion in to-expression has now been implemented.

**Comment by kidimbwi** [comment]
excellent! Thank you for looking into this and implementing this, your effort is greatly appreciated.
