### ISSUE TITLE
FR: RPN with spaces

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#207]
I was used to my HP48sx, where you could use a space (instead of ENTER) in RPN.
So, one could type `1 5+` and it would return `6`. No need to press ENTER two times...

What do others think?! Could this be an issue someplace else? Or is just silly?

**Comment by hanna-kn** [comment]
If you activate Mode->Parsing Mode->RPN syntax, and disable RPN mode or "use keyboard keys for RPN" (in preferences), you can type `1 5+` and 6 will be returned (after Enter or = is pressed).

If both RPN mode and syntax is active, then the expression `1 5` followed by RPN addition operation unfortunately returns 2 (only 1 is added to the stack, since the RPN syntax does not add values to the stack of the RPN mode.

**Comment by foreachthing** [comment]
Ok, gotcha!
Thanks. This works for my purpose just fine! 👍
