### ISSUE TITLE
[Bug] Crash when closing program

### ISSUE THREAD

**Issue by shedric1** [Qalculate/qalculate-gtk#211]
This is a pretty subtle bug, and likely unimportant since it only happens on close, but Qalculate GUI seems to be crashing on every exit under certain circumstances, at least on Windows 10.

Steps to reproduce:

1. Unpack portable Qalculate version 3.13.0 or newer into new folder for clean install
2. Run qalculate.exe (to generate user folder)
3. Close qalculate.exe
4. Run qalculate.exe again
5. Close qalculate.exe again

For me, this will generate:
a new crash dump in `C:\Users\$USER\AppData\Local\CrashDumps`   
a WER report in `C:\ProgramData\Microsoft\Windows\WER\ReportArchive`

Troubleshooting:
* It only happens for versions after 3.12.1. That version and several before it did not have this issue. It only starts with 3.13.0
* It only seems to happen if `qalculate-gtk.cfg` exists in the user settings directory. Closing Qalculate on a fresh install or deleting that file before opening allows graceful close.

Testing was done using the 32-bit zip for self-contained Windows usage. Let me know if any additional info would be useful.

**Comment by hanna-kn** [comment]
I can confirm this issue. It occurs with both the 32-bit zip and the 32-bit installation file (msi), but not with the 64-bit version. When running the same executable from the MingW/MSYS2 terminal, it does not occur.

It is likely not caused by any changes in the code of Qalculate, but related to the fact that the included program libraries were updated for version 3.13.0.

Although annoying, it is completely harmless.

If I remove the following code from the function called before exiting, Qalculate will not crash on exit.
```
if(view_thread->running) {
	view_thread->write(0);
	view_thread->write(NULL);
}
```
This code, and all Qalculate code the follows after, does however run successfully.

If I do not find a better solution, I will simply compile the 32-bit Windows binaries, for the next version of Qalculate, without the above code.

**Comment by shedric1** [comment]
I just checked version 3.17.0 and this issue no longer seems to be present. I'll go ahead and close this issue as resolved. 

Thanks for the fix!
