### ISSUE TITLE
Division by zero gives zero

### ISSUE THREAD

**Issue by fastjack77** [Qalculate/qalculate-gtk#228]
Dividing by zero gives zero. E.g. 0/0 = 0/0. Shouldn't it be _undefined_?

P.S. I'm not an expert in maths.

Edit: Qalculate! (GTK+) 3.3.0

**Comment by hanna-kn** [comment]
> Dividing by zero gives zero. E.g. 0/0 = 0/0. Shouldn't it be undefined?

0/0 = 0 would be wrong, but whether 0/0 should return 0/0 or undefined is a matter of preferences.

Generally Qalculate prefers to return the undefined expression, instead of "undefined". For more complex expression, this should give the user a better starting point for finding mistakes in the original expression.

In some contexts (if the value isn't actually exactly zero, but approaches zero from a specific direction)  division by zero might be defined.
