### ISSUE TITLE
Scientific notation should only be used to make reading easier

### ISSUE THREAD

**Issue by Hi-Angel** [Qalculate/qalculate-gtk#26]
E.g.:

	> 0x823445d

	  1.3652899E8 = approx. 1.3652899E8

There's no point to use scientific notation in the example, because the answer is `136528989`.

Here's a general rule: if scientific notation makes amount of symbols in the result bigger than the usual print, it should not be used.

E.g. `1000` vs `1e3` — it is justified, 4 vs 3 symbols. `10` vs `1e1` — it is *not* justified, scientific notation makes it longer.

And why the result is even approximated, I can't get an approximate file size!

**Comment by hanna-kn** [comment]
This behaviour is controlled by the precision setting. This setting affects both the precision of floating point calculations and the number of significant digits shown in auto "exp mode". The result is approximated to reduce the number of digits displayed. Increase precision (`set precision`), change exp mode (`set exp mode`) to off or a sufficiently large positive number, or activate fractional display (`set fractions on`), to modify this behaviour.

I will change the current behaviour so that, in auto "exp mode", scientific notation will be activated for exact values when the number of digits are greater then precision plus 3 (when precision >= 8). 

It would be problematic to show all digits of extremely large exact number by default (e.g. 12345678! ≈ 1,4572605E82187904).

**Comment by Hi-Angel** [comment]
Thanks, using `set precision 20` indeed prints whole number. Anyway, why not to just compare amount of characters, to decide whether scientific notation worth it for particular result? Such behavior would match peoples' thinking — people use the notation as a shorthand.

> It would be problematic to show all digits of extremely large exact numbers by default (e.g. 12345678! ≈ 1,4572605E82187904).

I understand, but this can be shortened with disregard to using or not the notation. E.g. `≈14572605…`.

**Comment by hanna-kn** [comment]
For approximate values, scientific notation is necessary for large numbers to indicate the number of significant digits, which is primarily controlled by the precision setting. In this case 1e1 (for a value > 5 and < 15) actually makes sense. 

Very large numbers becomes difficult to read (if they are small enough to not consume all available RAM). It takes much longer to see that 123456578901234 equals approximately 100 trillion, compared to 1.2345658901234e14, just as it normally makes more sense to write 1.23 terabyte instead 1233443243234 byte.

The question then becomes where to draw the line and if all or only limited number of decimals should be displayed for exact numbers in scientific notation. I decided to let the precision setting primarily determine this to make the display of exact and approximate numbers similar.

> I understand, but this can be shortened with disregard to using or not the notation. E.g. ≈14572605….
Do you suggest that it is adequate to display ≈14572605… as result for 12345678! ? The information about the size of the result would be totally lost.

**Comment by Hi-Angel** [comment]
> It takes much longer to see that 123456578901234 equals approximately 100 trillion, compared to 1.2345658901234e14

Aaah, indeed, never thought about it. The more you know… I'm probably closing the bug then, you better know it than me.
