### ISSUE TITLE
How to add qalculate as a gnome shell provider 

### ISSUE THREAD

**Issue by mbousq** [Qalculate/qalculate-gtk#298]
Hi. Qalculate does not appear as a gnome shell provider (tried with the flatpak, snap version and looked in the preference settings in the app). What am I missing ? Thank you for this calculator !

**Comment by hanna-kn** [comment]
The gnome shell search provider files were not included in the flatpak and snap versions. I've now updated the flatpak package with the search provider enabled (I've not tested if it works). I'm unsure if there's yet support for search providers in snap packages.

**Comment by mbousq** [comment]
Hi, thank you very much ! I works perfectly :)

**Comment by mbousq** [comment]
sorry my bad, I wrote too quickly. It still doesn't on flatpak. Having said that I installed the deb and it works perfectly. Please close this unless you want to keep it for future work. Thank you very much for everything.

**Comment by lunaryorn** [comment]
Doesn't work for me either; I see a search provider with the distribution-provided package, but not with this flatpak.

**Comment by lunaryorn** [comment]
@hanna-kn I think this is caused by a mismatch between the desktop ID specified in the search provider and the desktop file flatpak installs.

Flatpak installs the desktop entry as `io.github.Qalculate.desktop` but the [search provider refers to `qalculate-gtk.desktop`](https://github.com/Qalculate/qalculate-gtk/blob/82ed9071dc7d42be596bf043337eaf95e083c6e2/data/io.github.Qalculate.search-provider.ini#L2) which only gets installed by regular installations.

After replacing `DesktopId=qalculate-gtk.desktop` with `DesktopId=io.github.Qalculate.desktop` in
`/var/lib/flatpak/exports/share/gnome-shell/search-providers/io.github.Qalculate.search-provider.ini` the search provider appears in settings and in the search.

I can submit a fix for this, but I'm unsure where.  Should I submit a change to patch the search provider ini file to the [flatpak repo](https://github.com/flathub/io.github.Qalculate) or should I submit a pull request to rename the desktop entry in this repository to match the app ID convention of flatpak?

**Comment by hanna-kn** [comment]
> I can submit a fix for this, but I'm unsure where. Should I submit a change to patch the search provider ini file to the flatpak repo or should I submit a pull request to rename the desktop entry in this repository to match the app ID convention of flatpak?

I've now added a patch to the flatpak repository.

**Comment by lunaryorn** [comment]
@hanna-kn Thank you very much :+1: I'll try it and report whether it worked.

**Comment by lunaryorn** [comment]
@hanna-kn Thanks again, the search provider from the flatpak installation works perfectly now :pray: 

I guess you can close this issue :slightly_smiling_face:

**Comment by mbousq** [comment]
I can confirm it works as well :), thx!. Closing the issue.
