### ISSUE TITLE
"Fetching exchange rates" blocks UI

### ISSUE THREAD

**Issue by unhammer** [Qalculate/qalculate-gtk#30]
When I type "42 USD to GBP", there's a blocking popup saying `Fetching exchange rates`. 

It'd be really nice if, instead, we just got the result right away using cached/possibly stale exchange rates, but with a notice that `Exchange rates are being updated in the background, sit tight and your result will be updated once they're fetched`.

**Comment by hanna-kn** [comment]
With a reasonably fast Internet connection the popup will not even appear, and users with really slow and unstable connections should probably disable automatic exchange rate updates.

I've now however changed tthe behaviour so that the result is displayed before automatic retrieval of new exchange rates. Not blocking the ui is more problematic.
