### ISSUE TITLE
Plotting Help: Plot Chi-Square Distribution from 0 to 10 with DoF from 1 to 5

### ISSUE THREAD

**Issue by rickhg12hs** [Qalculate/qalculate-gtk#339]
Is it possible to plot the Chi-Square distribution from say, 0 to 10, AND with degrees of freedom from 1 to 5 ... in one function definition?

I.e., I know how to plot the distribution for a single DoF, and I know how to make multiple plots, but is there a way with a single function definition to cycle through multiple DoFs and plot them all at once?  Maybe create a matrix somehow?

**Comment by hanna-kn** [comment]
You need to use the plot() function, instead of the plot dialog (if using the latest released version - support for multiple series in a single expression was added to the GUI a few minutes ago).

Alternatives:
`plot([chisqdist(x,1),chisqdist(x,2),chisqdist(x,3),chisqdist(x,4),chisqdist(x,5)],0,10)`
`plot(genvector(chisqdist(x,y),1,5,1,y,1),0,10)`
`plot(chisqdist(x,[1,2,3,4,5]),0,10)`

The last alternative does unfortunately not work for chisqdist() (but does for most other functions) with the latest version. Function argument testing was aborted after illegal value x was detected as first argument, before detection of the vector in the second argument. This has been now fixed.

**Comment by rickhg12hs** [comment]
Works great!  Thanks!
