### ISSUE TITLE
Incorrect byte counting math for 'B' postfix 

### ISSUE THREAD

**Issue by owentroe** [Qalculate/qalculate-gtk#483]
Version: 4.6.1, GTK

Qalculate does not convert hex literals correctly when 'B' is used in place of 'byte'

### Example 1
![image](https://github.com/Qalculate/qalculate-gtk/assets/12129674/5f7ffa90-264f-4a8c-8f2c-b44f8f4b2f16)

Expected result:
![image](https://github.com/Qalculate/qalculate-gtk/assets/12129674/e56360f7-658f-47bd-84ea-586ea1fc13fe)

### Example 2

The equivalent decimal value works as expected: 

![image](https://github.com/Qalculate/qalculate-gtk/assets/12129674/c4f3bd68-0f14-491a-97ef-e0f5a091d30e)

### Example 3

The 'byte' postfix works as expected:

![image](https://github.com/Qalculate/qalculate-gtk/assets/12129674/1f327892-a20b-4575-ba47-99c36ee8287f)

### Example 4

Interestingly 'byte' does not work if a space is not left between the literal and postfix:

![image](https://github.com/Qalculate/qalculate-gtk/assets/12129674/a4c3e819-bead-458d-8277-918d0ef312ba)

(Note: a space was not found to change the behavior for 'B')

**Comment by hanna-kn** [comment]
B is interpreted as a hexadecimal digit.

**Comment by hanna-kn** [comment]
The hexadecimal number `0x40000B` equals `4 194 315` (in base 10). `4 194 315 bytes` equals approximately `4096 KiB`. Since `0x40000B` does not include a unit, the program assumes that you want to convert from bytes and appends this unit to the parsed expression. Whitespace is used as digit group separator and does therefor not change this behaviour.

When interpreting `0x40000byte`, the program reads this as a number until a non-valid hexadecimal digit (`y`) is encountered. In the absence of whitespace it is assumed that the number ends with the last valid digit and `yte` thus remains of the expression.

**Comment by owentroe** [comment]
I see, it’s obvious when you explain it. Thank you!
