### ISSUE TITLE
Bug in special functions besselj and bessely of Qalculate!  (qalculate-4.8.0-x64.msi)

### ISSUE THREAD

**Issue by braatjoseph** [Qalculate/qalculate-gtk#491]
On the calculator Qalculate! (classic), version 4.8.0. for Windows 10 (x64). I found the following issue:
A functions besselj(n,x) produces an output that is independent of the value of 'x'. However, this value changes when 'n'is varied.
Examples for besselj(n,x): 
besselj(0,0)=0 for all x (e.g. besselj(0,1000000)=1)
besselj(1,0)=besselj(1,1000000.0)=0.4400505857
besselj(-1,0)=besselj(-1,1000000.0)=0.7651976866
Examples for bessely(n,x):
bessely(0,0)  not defined but
bessely(1,0)=bessely(1,1000000.0)=-0.7812128213

On the calculator Qalculator from the Windows App Store I did not find the above bugs for besselj on the Qalculate! calculator.
However, I discovered the following inconsistency on Qalculator: 
besselj(0,0.0)=0  
and
besselj(0,0.000001)=0.999999999999750000000000

**Comment by braatjoseph** [comment]
Sorry for my typo on the first line with examples for besselj(n,x).
I should have written:
 besselj(0,0)=1 for all x (e.g. besselj(0,1000000)=1)

**Comment by hanna-kn** [comment]
Fixed.

In version 4.7, the fix for besselj(0, 0) broke besselj(0, x), for x ≠ 0.
In version 4.8, besselj(n, x) where accidentally changed to use the first argument for both order and parameter.
It is quite embarrassing how such serious bugs could be introduced and not be found before release.
I will try to release a fixed version as soon as possible.
