### ISSUE TITLE
I am using version 5.0.0, but I didn't get the right results. 

### ISSUE THREAD

**Issue by Ruxend** [Qalculate/qalculate-gtk#525]
This is the current return result:
![image](https://github.com/Qalculate/qalculate-gtk/assets/39160687/592c0347-88f4-4417-98e3-252a7905613e)
This is what should be returned:
![image](https://github.com/Qalculate/qalculate-gtk/assets/39160687/77eb5838-43bd-45a6-a793-1d5cd7c2e980)

**Comment by hanna-kn** [comment]
This is standard calculator behaviour. See https://github.com/Qalculate/libqalculate/issues/208#issuecomment-658897138 and https://github.com/Qalculate/libqalculate/issues/242.

Do avoid potential confusion, I've now made changes so that Qalculate will ask the user for the desired interpretation of percentage addition.

**Comment by hanna-kn** [comment]
This behaviour can be changed by disabling "simplified percentage calculation" (under `Mode->Parsing Mode` menu in qalculate-gtk, `Preferences->Parsing & Calculation` in qalculate-qt, or using `set percent 0` in qalc).

**Comment by Ruxend** [comment]
Got it. Thank you so much.
