### ISSUE TITLE
approximation?

### ISSUE THREAD

**Issue by quiricada** [Qalculate/qalculate-gtk#560]
11720000−32092.88
gave approximate result 11 687 907?
is there internal rule that:  less than certain percentage, it defaults to approximation?
shouldn't this be an option and general default on exact result?
i was doing some calculations and just copy/pasting the numbers and the results was off! went through the calculations and saw the approximation sign.

p.s. minor quibble, copy result use "space" as thousand separator, it crashes one of the program that i use (it can handle comma as thousand separator but not "space"), how about thousand separator as a user fillable option?

pps. i use copy result, is there a way to put a wee button on the side to click to copy result? or double click the result to copy result?

thanks mucho

**Comment by hanna-kn** [comment]
The maximum number of digits displayed, by default, is controlled by Mode➞Precision. 11 687 907 is shown if precision is set to 8, instead of the default 10.

> p.s. minor quibble, copy result use "space" as thousand separator, it crashes one of the program that i use (it can handle comma as thousand separator but not "space"), how about thousand separator as a user fillable option?

There are options in preferences to change the thousands separator (digit grouping), or copy the result as unformatted ASCII by default (this can also be achieved by selecting the appropriate copy option in the Edit menu or the context menu of the result field).

> pps. i use copy result, is there a way to put a wee button on the side to click to copy result? or double click the result to copy result?

Single click copies the result. (It is also possible to add a custom button which copies the result to the keypad.)

**Comment by quiricada** [comment]
apologies, rtfm and update :)
my slack and qalculate been working fine, just checked, was running version 3!
swiss army knife!
thanks
