### ISSUE TITLE
Sum of two dollar amount automatically converted to euros

### ISSUE THREAD

**Issue by Jonrysh** [Qalculate/qalculate-gtk#62]
Here's the history taken from Qalculate.  As you see, the sum of two dollar amounts is automatically converted to euros.  How can I simply have the sum displayed as dollars?
> RPN Operation = (454.06 × dollar) + (2736.98 × dollar)
> ≈ €2702.439
> 
> $2,736.98 = dollar × 2736.98
> = $2736.98
> 
> $454.06 = dollar × 454.06
> = $454.06

Thanks - jon

**Comment by hanna-kn** [comment]
There are several alternatives.

If you weren't using RPN, my main suggestion would be to type "$454.06+$2736.98 to $" (which informs me that I should add the possibility to use the 'to' operator on the stack in the GUI). You will still have the option to use one of the menus (or the conversion tab) for explicit conversion to USD, but this is not very efficient (unless using the CLI program).

Another alternative is to disable automatic unit conversion (Mode->Unit Display->No Additional Conversion).

If USD is your local/main currency you should consider changing the system-wide currency.

The most efficient option would usually be to not use any units when the unit is equal in all terms and in the expected result, since it makes no practical difference.

If I've interpreted your post correctly $2,736.98 and $454.06 is _not_ automatically converted to €? In recent versions those expressions should also be converted to the local currency, if automatic unit conversion is enabled.

**Comment by Jonrysh** [comment]
_hanna-kn writes:_
_If you weren't using RPN, my main suggestion would be to type "$454.06+$2736.98 to $" (which informs me that I should add the possibility to use the 'to' operator on the stack in the GUI). You will still have the option to use one of the menus (or the conversion tab) for explicit conversion to USD, but this is not very efficient (unless using the CLI program)._
I am using RPN.  
Typing "$454.06+$2736.98 to $ <CR>" does not convert ro euro.  
Typing "$454.06+$2736.98<CR>" does not convert to euro.
Typing "$454.06<CR> $2736.98<CR> <Keypad+>"  does convert to euro

_Another alternative is to disable automatic unit conversion (Mode->Unit Display->No Additional Conversion)._
This works fine.

_If USD is your local/main currency you should consider changing the system-wide currency._
How is the system-wide currency set?

_The most efficient option would usually be to not use any units when the unit is equal in all terms and in the expected result, since it makes no practical difference._
Why do I do this?  The easiest cut+paste (double click) from text picks up the dollar signs; otherwise I have to either select the numbers and not the dollar signs, or else edit the dollar signs out in qalculate.

_If I've interpreted your post correctly $2,736.98 and $454.06 is not automatically converted to €? In recent versions those expressions should also be converted to the local currency, if automatic unit conversion is enabled._
They are not converted to euro when entered, only after the "+" operation.

Thanks for your quick reply and for this excellent program.

jon

BTW: My ISP, which is ATT, doesn't understand the reply address generated by github.  I am going to report the problem to github (no point in telling ATT).

**Comment by hanna-kn** [comment]
> Typing "$454.06+$2736.98" does not convert to euro.

This should only be true if version <= 2.2.1. Automatic conversion to local currency was introduced in version 2.3 (after a request). I will considering adding an option to disable automatic unit conversion to local currency.

For version <= 2.2.1 the behaviour in RPN mode is clearly a bug, but for later versions this (in this case unfortunately) the expected behaviour (although the bug did still exists for other units before I fixed it a few moments ago).

> Why do I do this? The easiest cut+paste (double click) from text picks up the dollar signs; otherwise I have to either select the numbers and not the dollar signs, or else edit the dollar signs out in qalculate.

I was thinking of a non-cut+paste situation...

> How is the system-wide currency set?

That depends on the operating system/distribution/desktop environment used. It can be set temporarily on the command line using `LC_MONETARY=en_US qalculate-gtk`, on GNU/Linux.

**Comment by hanna-kn** [comment]
Version 2.6.2 fixes the remaining related bugs and adds an option to disable automatic conversion to the local currency.
