### ISSUE TITLE
Feature request: Bring up old input values with arrow keys

### ISSUE THREAD

**Issue by haarp** [Qalculate/qalculate-gtk#7]
Hey, I think it would be convenient if one could bring up old inputs from the history in the input box by pressing arrow up/down, the same way it works in most shells :)

Cheers!

**Comment by hanna-kn** [comment]
That functionality is currently implemented using page up and page down instead of the arrow keys, mainly because up and down are used for completion.

**Comment by haarp** [comment]
Oh, I see, good to know. Thanks! :)

**Comment by regs01** [comment]
Is it possible to disable history on arrows?

**Comment by hanna-kn** [comment]
> Is it possible to disable history on arrows?

Not currently.
Why do you want to disable history on arrows?

**Comment by regs01** [comment]
Some problematic to use arrow keys to navigate long expressions. Accident additional press up will bring the previous expression. PGUP and PGDN is enough for that.

**Comment by hanna-kn** [comment]
> Some problematic to use arrow keys to navigate long expressions. Accident additional press up will bring the previous expression. PGUP and PGDN is enough for that.

Instead of adding another option, I've modified the default behaviour (in version 3.16.0).

Up/down will now only cycle through the expression history when the text cursor is at the beginning or end of the expression and the action will not switch during auto repeat.

The current expression is now included in the expression history and, if you accidentally press up (and bring up the previous expression), you can thus easily restore the edited expression by pressing down (the same could previously be achieved using Ctrl+Z).

Let me know if an option to completely disable history on arrows is still needed.
